### ISSUE TITLE
Doesn't work in Safari 9.0.2

### ISSUE THREAD

**Issue by omandryk** [adaojunior/english-verbs#5]
Hi, I've tried to use english-verbs on Safari, but it doesn't work. There are multiple errors in the console:
![screen shot 2016-01-10 at 4 08 14 pm](https://cloud.githubusercontent.com/assets/2678920/12222165/71ca8bbc-b7b4-11e5-9b0b-f37555c1d730.png)

**Comment by adaojunior** [comment]
@icoderman thanks, I just uploaded a temporary fix, it was a problem with media query.
https://github.com/adaojunior/ng_mediaquery/blob/master/lib/ng_mediaquery.dart#L23
https://github.com/adaojunior/english-verbs/blob/master/lib/src/components/conjugation-view/conjugation-view.html#L1
I will take a look if this is a dart bug or if safari doesnt support `matchMedia`.
Again, thanks for reporting

**Comment by adaojunior** [comment]
https://github.com/dart-lang/sdk/issues/23784
